### ISSUE TITLE
Manage Float

### ISSUE THREAD

**Issue by Margaferrez** [mikeywaites/kim#152]
We are using Kim in our project. We like it a lot, is simple and easy to work with.
We had to return Float as field when marshalling. We've implemented as a custom  field, and I was thining that can be implemented in the core.
I'll be happy to create a PR with the changes if you consider is going to be useful for other users.

**Comment by mikeywaites** [comment]
Hey @Margaferrez 

So firstly, thanks for getting in touch.  It's great to hear people are finding Kim useful.  We're more than happy to accept pr's for these changes you've propose.  We had actually been discussing introducing some Fields and Pipelines from our code base that we felt we're useful in the core code base so thanks for lighting a fire under us 👍 

I've gone ahead and started a base branch for the release.  Everything will be merging there so please create your PRs with `release/1.2.0` as the target branch.  We will be putting some more issues in later today to track the fields and changes we're going to make on this release too!

Look forward to reviewing your PRs!

#155
