### ISSUE TITLE
allow_none=False and required=False no action

### ISSUE THREAD

**Issue by dimonji** [mikeywaites/kim#177]
Hi. When I define field in my Mapper 
```
value = field.Integer(allow_none=False, required=False)
```
And when I serialize my data I get {'value': None}. Is the logic correct? 
In mapper I use only __default__ role

**Comment by mikeywaites** [comment]
HI @dimonji 

Thanks for reaching out.  So just to clarify what you're trying to define here is a field that is not required (IE wont raise validation errors if the field is absent) BUT will raise a validation error for any value that is not an integer 

If you could also include a small example of the data you're passing to your mapper as well so i can replicate.

**Comment by dimonji** [comment]
Ok, sure, simple example
```
# -*- coding: utf-8 -*-
import asyncio
import datetime

from kim import Mapper, field, whitelist


class KeywordSearchVolume(Mapper):
    __type__ = dict

    id = field.String()
    keyword_id = field.String()
    location_id = field.Integer()
    date = field.Date()
    value = field.Integer(required=False, allow_none=False)

    __roles__ = {
        'rabbitmq': whitelist('id', 'keyword_id', 'location_id', 'date')
    }

a = {'id': '2df7d86069a30ac54f04153c33a6f854',
     'keyword_id': '08d0a052a774b7a5306bb4685e7a7da0',
     'location_id': 93138,
     'date': datetime.date(2018, 2, 1)}


async def main(loop):
    map = KeywordSearchVolume(obj=a).serialize()
    print(map)


loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))

```

**Comment by mikeywaites** [comment]
Hey @dimonji 

Sorry for the slow reply.  So if you're expecting a validation error here the issue is that you're serializing and not marshaling.  Validation is not applied during serialization. 

I've not checked if this is an issue that occurs when marshaling yet but I will defo get a test case together tonight.

**Comment by dimonji** [comment]
Yes, I was think if I set required=False, allow_none=False, after serialize
this field will be not present in the results dataset

ср, 6 мар. 2019 г. в 18:10, Mike Waites <notifications@github.com>:

**Comment by mikeywaites** [comment]
Unfortunately that logic is only applied when marshaling.  This functionality could be achieved with the use of a custom serialization pipe[1] however, this would be on a per field level.  The internals that sets the field value to the output is a "pipe" itself [2].  This would be difficult to change everywhere without some monkey patching.

With those points in mind, and the assumption that you want this "remove None" logic to be applied to all data whilst serializing, I think it would be better to override the serialize method on the Mapper in a custom base mapper.  Here's an example of that in action.

```
class MyBaseMapper(Mapper):
    def serialize(self, role='__default__', raw=False, deferred_role=None):
        output = super(MyBaseMapper, self).serialize(role='__default__', raw=False, deferred_role=None)
        # Now you can iterate over output to find anything that should be removed etc..
        return output
```

I hope that helps and please don't hesitate to reach out if you'd like some more help

[1]  - https://kim.readthedocs.io/en/latest/user/advanced.html#custom-fields-and-pipelines
[2] - https://github.com/mikeywaites/kim/blob/master/kim/pipelines/base.py#L289

**Comment by dimonji** [comment]
Thank you.
